services:
  gluetun_qbittorent_port_manager:
    image: gluetun_qbittorent_port_manager
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - HOST=192.168.1.1 # CHANGE TO YOUR HOST IP
      - PORT=8080 # CHANGE_TO YOUR PORT
      - USERNAME=username # CHANGE TO YOUR USERNAME
      - PASSWORD=password # CHANGE TO YOUR PASSWORD
    volumes:
      - /home/:/gluetun